CREATE TABLE MEMBER
(

	MEMBER_CODE VARCHAR2(50) NOT NULL,
	USER_NAME VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(200) NOT NULL,
	ADDRESS VARCHAR2(200) ,
	PHONE VARCHAR2(20) NOT NULL,
	MEMBER_TYPE VARCHAR2(20) NOT NULL,
	SALARY NUMBER(20) NOT NULL,
);