package com.demo.service.impl;

import java.util.Arrays;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;
import com.demo.model.Member;
import com.demo.repository.MemberRepository;
import com.demo.service.MemberService;


@Service(value = "memberService")
public class MemberServiceImpl implements UserDetailsService,MemberService{
	

	@Autowired
	private MemberRepository memberRepository;	

	public MemberServiceImpl(MemberRepository memberRepository) {
		this.memberRepository = memberRepository;
	}

	@Override
	public Member save(Member member) {
		// TODO Autogenerated method stub
		return memberRepository.save(member);
	}

	@Override
	public Member getMemberByUserName(String userName) {
		// TODO Autogenerated method stub
		return memberRepository.findByUsername(userName);
	}	

	@Override
	public Member getMemberById(String memberCode) {
		// TODO Autogenerated method stub
		return memberRepository.findOne(memberCode);
	}

	@Override
	public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
		Member member = memberRepository.findByUsername(username);
		if(member == null){
			throw new UsernameNotFoundException("Invalid username or password.");
		}
		return new org.springframework.security.core.userdetails.User(member.getUsername(), member.getPassword(), getAuthority());
	}	

	private List<SimpleGrantedAuthority> getAuthority() {
		return Arrays.asList(new SimpleGrantedAuthority("ROLE_ADMIN"));
	}
}


